# Generated by Django 3.1.7 on 2021-03-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pdfs',
            field=models.CharField(max_length=255),
        ),
    ]
